# Generated by Django 5.2.4 on 2025-07-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='year_model',
        ),
    ]
