# Generated by Django 5.2.4 on 2025-07-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_year_car_year_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year_model',
            new_name='model_year',
        ),
    ]
